### ISSUE TITLE
Know any algorithm in Javascript?

### ISSUE THREAD

**Issue by abranhe** [AllAlgorithms/javascript#1]
<p align="center">
  <img src="https://cdn.abraham.gq/projects/algorithms/algorithms.svg">
</p>

Hi, everyone! 

> Do you know any algorithm implementation in any language, that you wanna share with us?

Open a pull request in any of the programming languages available, or in [Javascript](https://github.com/AllAlgorithms/javascript) this case

**Comment by juanarbol** [comment]
Fibonacci serie is ok?

**Comment by ajitid** [comment]
Doing GCD and spiral matrix against this issue for `math/`. Or I can open new issues for each algo and you can label them as Hacktoberfest.

Pull request at #35

**Comment by mayakarabula** [comment]
Added BFS and DFS https://github.com/AllAlgorithms/javascript/pull/34 @abranhe

**Comment by versavale** [comment]
Added #42
